language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
dist: xenial
addons:
    apt:
      packages:
        - rabbitmq-server
services:
  - rabbitmq
#deploy:
#  provider: pypi
#  distributions: sdist bdist_wheel
#  user: "__token__"
#  password:
#    secure: IvQPFwa2oaZ8hRZdrxVImazhu0myknqnUzO+ZCc72TpBUNH/D6QXCfVZRwv4VkHbNAggJuZPYyDHi6/xSd7yup+flCNCWVa+aC0+exBm7eCEXZC+mBXrJ9LauMT4EVyR13YsfZZzLtxT3pg/8dyDhjvneZBbHmIxSoS5dGFzclPcCe1t2XXexsSeS8+8rkan3+pG6t0GWAz/fuq4jWO9w6rCjRVFtWKqFG8Jbeezh9A0tDHY4GrIG4U3TjDseKj0yj2ozLL7WHs6N7D+DHSMPuJMQQBDxGmiWPLT8LfGJ9eylzWx/CZaLpiVo4/17tlSliofVDjcXdBcbAdWDfw4rCgvjllOcGgQAqMYZYwF5nsdkzhDNXNtEObfb9AGbWG9/TbrlfmbHiFXCKbE5U88cwGM4sEKxZC/x6e+ZHFFxPAIQ6A1l5j3nJA8AYGCbVgJ7utvrMqFtBhe5gZaEUfUDap0+5l8x4G+oiEIZsSYAeWCBYkJRumeCLEniCI2W+hOM5/Ch/PIfcHjaJuCqYubIb8MxjZNXBI/mnUH/SSaRGxs5j0n8e4D1zBdcsFzoBIrfDOLrb5lC/NWYiUm4PrAX5YzfaKw+8GaVkubFRxyqtfYN+L6SIpL5hqfn802Q5f8ozCMLCQUv49JP+DjW4AYgrVm44b19HbNpDDVgHDHrpo=
#  on:
#    branch: master
#    tags: true
#    repo: nidhaloff/b_rabbit
#    python: 3.7
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
